#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: 'project'}
- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Alquileres Meli',  url: 'AlquileresMeli'}

#-------------------------------
# Projects Section

projects:
- {name: 'Project One',   url: 'proj-1'}
- {name: 'Project Two',   url: 'proj-2'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://github.com/NahuelZanzi'}
- {icon: 'github',    link: 'https://github.com/NahuelZanzi'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/nahuel-martin/'}


seo:
  description: 'Mi portfolio personal hecho Jekyll y GitHub Pages'

#-------------------------------
# Google Analytics Section

google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
